# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'

current_dir = File.dirname(File.expand_path(__FILE__))
variable = YAML.load_file("#{current_dir}/config.yaml")

Vagrant.configure("2") do |config|
  
  ###################################################################################
  ###################### Common Configuration for all machines ######################
  ###################################################################################
  
  config.vm.box = variable["vagrant-box"]

  config.vm.network :forwarded_port, guest: 3389, host: 3390, auto_correct: true
  config.vm.network :forwarded_port, guest: 5985, host: 5986, id: "winrm", auto_correct: true
  
  # Virtualbox provider specific configuration

  config.vm.provider "virtualbox" do |vb|
    vb.memory = variable["memory"]
    vb.cpus = variable["cpus"]
    vb.gui = true
    vb.linked_clone = true
    
    # Settings overview: https://www.virtualbox.org/manual/ch08.html#idp47569025503568

    vb.customize ["modifyvm", :id, "--vram", "128"]
    vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    vb.customize ["modifyvm", :id, "--draganddrop", "bidirectional"]
    vb.customize ["modifyvm", :id, "--audio", "none"]
  end
  
  # Shell provisioning script running on guest

  config.vm.provision "shell" do |script|
    script.args = [ variable["ravendb"]["installer"] ]
    script.path = variable["ravendb"]["installer-script"]
  end
  
  #######################################################################
  ###################### Per Machine Configuration ######################
  #######################################################################
    
  variable["machines"].each do |machineConfig|
    config.vm.define machineConfig["name"] do |machine|
      machine.vm.hostname = machineConfig["name"]
      machine.vm.network machineConfig["network"], ip: machineConfig["ip"]
        
      config.vm.provider "virtualbox" do |vb|
          vb.name = machineConfig["name"]
      end
    end
  end
end
